// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cartographer/mapping/proto/pose_extrapolator_options.proto

#ifndef PROTOBUF_cartographer_2fmapping_2fproto_2fpose_5fextrapolator_5foptions_2eproto__INCLUDED
#define PROTOBUF_cartographer_2fmapping_2fproto_2fpose_5fextrapolator_5foptions_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3004000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "csmlio/common/proto/ceres_solver_options.pb.h"
// @@protoc_insertion_point(includes)
namespace csmlio {
namespace mapping {
namespace proto {
class ConstantVelocityPoseExtrapolatorOptions;
class ConstantVelocityPoseExtrapolatorOptionsDefaultTypeInternal;
extern ConstantVelocityPoseExtrapolatorOptionsDefaultTypeInternal _ConstantVelocityPoseExtrapolatorOptions_default_instance_;
class ImuBasedPoseExtrapolatorOptions;
class ImuBasedPoseExtrapolatorOptionsDefaultTypeInternal;
extern ImuBasedPoseExtrapolatorOptionsDefaultTypeInternal _ImuBasedPoseExtrapolatorOptions_default_instance_;
class PoseExtrapolatorOptions;
class PoseExtrapolatorOptionsDefaultTypeInternal;
extern PoseExtrapolatorOptionsDefaultTypeInternal _PoseExtrapolatorOptions_default_instance_;
}  // namespace proto
}  // namespace mapping
}  // namespace csmlio

namespace csmlio {
namespace mapping {
namespace proto {

namespace protobuf_cartographer_2fmapping_2fproto_2fpose_5fextrapolator_5foptions_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static void InitDefaultsImpl();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_cartographer_2fmapping_2fproto_2fpose_5fextrapolator_5foptions_2eproto

// ===================================================================

class ConstantVelocityPoseExtrapolatorOptions : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:cartographer.mapping.proto.ConstantVelocityPoseExtrapolatorOptions) */ {
 public:
  ConstantVelocityPoseExtrapolatorOptions();
  virtual ~ConstantVelocityPoseExtrapolatorOptions();

  ConstantVelocityPoseExtrapolatorOptions(const ConstantVelocityPoseExtrapolatorOptions& from);

  inline ConstantVelocityPoseExtrapolatorOptions& operator=(const ConstantVelocityPoseExtrapolatorOptions& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ConstantVelocityPoseExtrapolatorOptions(ConstantVelocityPoseExtrapolatorOptions&& from) noexcept
    : ConstantVelocityPoseExtrapolatorOptions() {
    *this = ::std::move(from);
  }

  inline ConstantVelocityPoseExtrapolatorOptions& operator=(ConstantVelocityPoseExtrapolatorOptions&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const ConstantVelocityPoseExtrapolatorOptions& default_instance();

  static inline const ConstantVelocityPoseExtrapolatorOptions* internal_default_instance() {
    return reinterpret_cast<const ConstantVelocityPoseExtrapolatorOptions*>(
               &_ConstantVelocityPoseExtrapolatorOptions_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(ConstantVelocityPoseExtrapolatorOptions* other);
  friend void swap(ConstantVelocityPoseExtrapolatorOptions& a, ConstantVelocityPoseExtrapolatorOptions& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ConstantVelocityPoseExtrapolatorOptions* New() const PROTOBUF_FINAL { return New(NULL); }

  ConstantVelocityPoseExtrapolatorOptions* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const ConstantVelocityPoseExtrapolatorOptions& from);
  void MergeFrom(const ConstantVelocityPoseExtrapolatorOptions& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(ConstantVelocityPoseExtrapolatorOptions* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // double imu_gravity_time_constant = 1;
  void clear_imu_gravity_time_constant();
  static const int kImuGravityTimeConstantFieldNumber = 1;
  double imu_gravity_time_constant() const;
  void set_imu_gravity_time_constant(double value);

  // double pose_queue_duration = 2;
  void clear_pose_queue_duration();
  static const int kPoseQueueDurationFieldNumber = 2;
  double pose_queue_duration() const;
  void set_pose_queue_duration(double value);

  // @@protoc_insertion_point(class_scope:cartographer.mapping.proto.ConstantVelocityPoseExtrapolatorOptions)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  double imu_gravity_time_constant_;
  double pose_queue_duration_;
  mutable int _cached_size_;
  friend struct protobuf_cartographer_2fmapping_2fproto_2fpose_5fextrapolator_5foptions_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ImuBasedPoseExtrapolatorOptions : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:cartographer.mapping.proto.ImuBasedPoseExtrapolatorOptions) */ {
 public:
  ImuBasedPoseExtrapolatorOptions();
  virtual ~ImuBasedPoseExtrapolatorOptions();

  ImuBasedPoseExtrapolatorOptions(const ImuBasedPoseExtrapolatorOptions& from);

  inline ImuBasedPoseExtrapolatorOptions& operator=(const ImuBasedPoseExtrapolatorOptions& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ImuBasedPoseExtrapolatorOptions(ImuBasedPoseExtrapolatorOptions&& from) noexcept
    : ImuBasedPoseExtrapolatorOptions() {
    *this = ::std::move(from);
  }

  inline ImuBasedPoseExtrapolatorOptions& operator=(ImuBasedPoseExtrapolatorOptions&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const ImuBasedPoseExtrapolatorOptions& default_instance();

  static inline const ImuBasedPoseExtrapolatorOptions* internal_default_instance() {
    return reinterpret_cast<const ImuBasedPoseExtrapolatorOptions*>(
               &_ImuBasedPoseExtrapolatorOptions_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    1;

  void Swap(ImuBasedPoseExtrapolatorOptions* other);
  friend void swap(ImuBasedPoseExtrapolatorOptions& a, ImuBasedPoseExtrapolatorOptions& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ImuBasedPoseExtrapolatorOptions* New() const PROTOBUF_FINAL { return New(NULL); }

  ImuBasedPoseExtrapolatorOptions* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const ImuBasedPoseExtrapolatorOptions& from);
  void MergeFrom(const ImuBasedPoseExtrapolatorOptions& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(ImuBasedPoseExtrapolatorOptions* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // .cartographer.common.proto.CeresSolverOptions solver_options = 7;
  bool has_solver_options() const;
  void clear_solver_options();
  static const int kSolverOptionsFieldNumber = 7;
  const ::csmlio::common::proto::CeresSolverOptions& solver_options() const;
  ::csmlio::common::proto::CeresSolverOptions* mutable_solver_options();
  ::csmlio::common::proto::CeresSolverOptions* release_solver_options();
  void set_allocated_solver_options(::csmlio::common::proto::CeresSolverOptions* solver_options);

  // double pose_queue_duration = 1;
  void clear_pose_queue_duration();
  static const int kPoseQueueDurationFieldNumber = 1;
  double pose_queue_duration() const;
  void set_pose_queue_duration(double value);

  // double gravity_constant = 2;
  void clear_gravity_constant();
  static const int kGravityConstantFieldNumber = 2;
  double gravity_constant() const;
  void set_gravity_constant(double value);

  // double pose_translation_weight = 3;
  void clear_pose_translation_weight();
  static const int kPoseTranslationWeightFieldNumber = 3;
  double pose_translation_weight() const;
  void set_pose_translation_weight(double value);

  // double pose_rotation_weight = 4;
  void clear_pose_rotation_weight();
  static const int kPoseRotationWeightFieldNumber = 4;
  double pose_rotation_weight() const;
  void set_pose_rotation_weight(double value);

  // double imu_acceleration_weight = 5;
  void clear_imu_acceleration_weight();
  static const int kImuAccelerationWeightFieldNumber = 5;
  double imu_acceleration_weight() const;
  void set_imu_acceleration_weight(double value);

  // double imu_rotation_weight = 6;
  void clear_imu_rotation_weight();
  static const int kImuRotationWeightFieldNumber = 6;
  double imu_rotation_weight() const;
  void set_imu_rotation_weight(double value);

  // double odometry_translation_weight = 8;
  void clear_odometry_translation_weight();
  static const int kOdometryTranslationWeightFieldNumber = 8;
  double odometry_translation_weight() const;
  void set_odometry_translation_weight(double value);

  // double odometry_rotation_weight = 9;
  void clear_odometry_rotation_weight();
  static const int kOdometryRotationWeightFieldNumber = 9;
  double odometry_rotation_weight() const;
  void set_odometry_rotation_weight(double value);

  // @@protoc_insertion_point(class_scope:cartographer.mapping.proto.ImuBasedPoseExtrapolatorOptions)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::csmlio::common::proto::CeresSolverOptions* solver_options_;
  double pose_queue_duration_;
  double gravity_constant_;
  double pose_translation_weight_;
  double pose_rotation_weight_;
  double imu_acceleration_weight_;
  double imu_rotation_weight_;
  double odometry_translation_weight_;
  double odometry_rotation_weight_;
  mutable int _cached_size_;
  friend struct protobuf_cartographer_2fmapping_2fproto_2fpose_5fextrapolator_5foptions_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class PoseExtrapolatorOptions : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:cartographer.mapping.proto.PoseExtrapolatorOptions) */ {
 public:
  PoseExtrapolatorOptions();
  virtual ~PoseExtrapolatorOptions();

  PoseExtrapolatorOptions(const PoseExtrapolatorOptions& from);

  inline PoseExtrapolatorOptions& operator=(const PoseExtrapolatorOptions& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  PoseExtrapolatorOptions(PoseExtrapolatorOptions&& from) noexcept
    : PoseExtrapolatorOptions() {
    *this = ::std::move(from);
  }

  inline PoseExtrapolatorOptions& operator=(PoseExtrapolatorOptions&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const PoseExtrapolatorOptions& default_instance();

  static inline const PoseExtrapolatorOptions* internal_default_instance() {
    return reinterpret_cast<const PoseExtrapolatorOptions*>(
               &_PoseExtrapolatorOptions_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    2;

  void Swap(PoseExtrapolatorOptions* other);
  friend void swap(PoseExtrapolatorOptions& a, PoseExtrapolatorOptions& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline PoseExtrapolatorOptions* New() const PROTOBUF_FINAL { return New(NULL); }

  PoseExtrapolatorOptions* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const PoseExtrapolatorOptions& from);
  void MergeFrom(const PoseExtrapolatorOptions& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(PoseExtrapolatorOptions* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // .cartographer.mapping.proto.ConstantVelocityPoseExtrapolatorOptions constant_velocity = 2;
  bool has_constant_velocity() const;
  void clear_constant_velocity();
  static const int kConstantVelocityFieldNumber = 2;
  const ::csmlio::mapping::proto::ConstantVelocityPoseExtrapolatorOptions& constant_velocity() const;
  ::csmlio::mapping::proto::ConstantVelocityPoseExtrapolatorOptions* mutable_constant_velocity();
  ::csmlio::mapping::proto::ConstantVelocityPoseExtrapolatorOptions* release_constant_velocity();
  void set_allocated_constant_velocity(::csmlio::mapping::proto::ConstantVelocityPoseExtrapolatorOptions* constant_velocity);

  // .cartographer.mapping.proto.ImuBasedPoseExtrapolatorOptions imu_based = 3;
  bool has_imu_based() const;
  void clear_imu_based();
  static const int kImuBasedFieldNumber = 3;
  const ::csmlio::mapping::proto::ImuBasedPoseExtrapolatorOptions& imu_based() const;
  ::csmlio::mapping::proto::ImuBasedPoseExtrapolatorOptions* mutable_imu_based();
  ::csmlio::mapping::proto::ImuBasedPoseExtrapolatorOptions* release_imu_based();
  void set_allocated_imu_based(::csmlio::mapping::proto::ImuBasedPoseExtrapolatorOptions* imu_based);

  // bool use_imu_based = 1;
  void clear_use_imu_based();
  static const int kUseImuBasedFieldNumber = 1;
  bool use_imu_based() const;
  void set_use_imu_based(bool value);

  // @@protoc_insertion_point(class_scope:cartographer.mapping.proto.PoseExtrapolatorOptions)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::csmlio::mapping::proto::ConstantVelocityPoseExtrapolatorOptions* constant_velocity_;
  ::csmlio::mapping::proto::ImuBasedPoseExtrapolatorOptions* imu_based_;
  bool use_imu_based_;
  mutable int _cached_size_;
  friend struct protobuf_cartographer_2fmapping_2fproto_2fpose_5fextrapolator_5foptions_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ConstantVelocityPoseExtrapolatorOptions

// double imu_gravity_time_constant = 1;
inline void ConstantVelocityPoseExtrapolatorOptions::clear_imu_gravity_time_constant() {
  imu_gravity_time_constant_ = 0;
}
inline double ConstantVelocityPoseExtrapolatorOptions::imu_gravity_time_constant() const {
  // @@protoc_insertion_point(field_get:cartographer.mapping.proto.ConstantVelocityPoseExtrapolatorOptions.imu_gravity_time_constant)
  return imu_gravity_time_constant_;
}
inline void ConstantVelocityPoseExtrapolatorOptions::set_imu_gravity_time_constant(double value) {
  
  imu_gravity_time_constant_ = value;
  // @@protoc_insertion_point(field_set:cartographer.mapping.proto.ConstantVelocityPoseExtrapolatorOptions.imu_gravity_time_constant)
}

// double pose_queue_duration = 2;
inline void ConstantVelocityPoseExtrapolatorOptions::clear_pose_queue_duration() {
  pose_queue_duration_ = 0;
}
inline double ConstantVelocityPoseExtrapolatorOptions::pose_queue_duration() const {
  // @@protoc_insertion_point(field_get:cartographer.mapping.proto.ConstantVelocityPoseExtrapolatorOptions.pose_queue_duration)
  return pose_queue_duration_;
}
inline void ConstantVelocityPoseExtrapolatorOptions::set_pose_queue_duration(double value) {
  
  pose_queue_duration_ = value;
  // @@protoc_insertion_point(field_set:cartographer.mapping.proto.ConstantVelocityPoseExtrapolatorOptions.pose_queue_duration)
}

// -------------------------------------------------------------------

// ImuBasedPoseExtrapolatorOptions

// double pose_queue_duration = 1;
inline void ImuBasedPoseExtrapolatorOptions::clear_pose_queue_duration() {
  pose_queue_duration_ = 0;
}
inline double ImuBasedPoseExtrapolatorOptions::pose_queue_duration() const {
  // @@protoc_insertion_point(field_get:cartographer.mapping.proto.ImuBasedPoseExtrapolatorOptions.pose_queue_duration)
  return pose_queue_duration_;
}
inline void ImuBasedPoseExtrapolatorOptions::set_pose_queue_duration(double value) {
  
  pose_queue_duration_ = value;
  // @@protoc_insertion_point(field_set:cartographer.mapping.proto.ImuBasedPoseExtrapolatorOptions.pose_queue_duration)
}

// double gravity_constant = 2;
inline void ImuBasedPoseExtrapolatorOptions::clear_gravity_constant() {
  gravity_constant_ = 0;
}
inline double ImuBasedPoseExtrapolatorOptions::gravity_constant() const {
  // @@protoc_insertion_point(field_get:cartographer.mapping.proto.ImuBasedPoseExtrapolatorOptions.gravity_constant)
  return gravity_constant_;
}
inline void ImuBasedPoseExtrapolatorOptions::set_gravity_constant(double value) {
  
  gravity_constant_ = value;
  // @@protoc_insertion_point(field_set:cartographer.mapping.proto.ImuBasedPoseExtrapolatorOptions.gravity_constant)
}

// double pose_translation_weight = 3;
inline void ImuBasedPoseExtrapolatorOptions::clear_pose_translation_weight() {
  pose_translation_weight_ = 0;
}
inline double ImuBasedPoseExtrapolatorOptions::pose_translation_weight() const {
  // @@protoc_insertion_point(field_get:cartographer.mapping.proto.ImuBasedPoseExtrapolatorOptions.pose_translation_weight)
  return pose_translation_weight_;
}
inline void ImuBasedPoseExtrapolatorOptions::set_pose_translation_weight(double value) {
  
  pose_translation_weight_ = value;
  // @@protoc_insertion_point(field_set:cartographer.mapping.proto.ImuBasedPoseExtrapolatorOptions.pose_translation_weight)
}

// double pose_rotation_weight = 4;
inline void ImuBasedPoseExtrapolatorOptions::clear_pose_rotation_weight() {
  pose_rotation_weight_ = 0;
}
inline double ImuBasedPoseExtrapolatorOptions::pose_rotation_weight() const {
  // @@protoc_insertion_point(field_get:cartographer.mapping.proto.ImuBasedPoseExtrapolatorOptions.pose_rotation_weight)
  return pose_rotation_weight_;
}
inline void ImuBasedPoseExtrapolatorOptions::set_pose_rotation_weight(double value) {
  
  pose_rotation_weight_ = value;
  // @@protoc_insertion_point(field_set:cartographer.mapping.proto.ImuBasedPoseExtrapolatorOptions.pose_rotation_weight)
}

// double imu_acceleration_weight = 5;
inline void ImuBasedPoseExtrapolatorOptions::clear_imu_acceleration_weight() {
  imu_acceleration_weight_ = 0;
}
inline double ImuBasedPoseExtrapolatorOptions::imu_acceleration_weight() const {
  // @@protoc_insertion_point(field_get:cartographer.mapping.proto.ImuBasedPoseExtrapolatorOptions.imu_acceleration_weight)
  return imu_acceleration_weight_;
}
inline void ImuBasedPoseExtrapolatorOptions::set_imu_acceleration_weight(double value) {
  
  imu_acceleration_weight_ = value;
  // @@protoc_insertion_point(field_set:cartographer.mapping.proto.ImuBasedPoseExtrapolatorOptions.imu_acceleration_weight)
}

// double imu_rotation_weight = 6;
inline void ImuBasedPoseExtrapolatorOptions::clear_imu_rotation_weight() {
  imu_rotation_weight_ = 0;
}
inline double ImuBasedPoseExtrapolatorOptions::imu_rotation_weight() const {
  // @@protoc_insertion_point(field_get:cartographer.mapping.proto.ImuBasedPoseExtrapolatorOptions.imu_rotation_weight)
  return imu_rotation_weight_;
}
inline void ImuBasedPoseExtrapolatorOptions::set_imu_rotation_weight(double value) {
  
  imu_rotation_weight_ = value;
  // @@protoc_insertion_point(field_set:cartographer.mapping.proto.ImuBasedPoseExtrapolatorOptions.imu_rotation_weight)
}

// .cartographer.common.proto.CeresSolverOptions solver_options = 7;
inline bool ImuBasedPoseExtrapolatorOptions::has_solver_options() const {
  return this != internal_default_instance() && solver_options_ != NULL;
}
inline void ImuBasedPoseExtrapolatorOptions::clear_solver_options() {
  if (GetArenaNoVirtual() == NULL && solver_options_ != NULL) delete solver_options_;
  solver_options_ = NULL;
}
inline const ::csmlio::common::proto::CeresSolverOptions& ImuBasedPoseExtrapolatorOptions::solver_options() const {
  const ::csmlio::common::proto::CeresSolverOptions* p = solver_options_;
  // @@protoc_insertion_point(field_get:cartographer.mapping.proto.ImuBasedPoseExtrapolatorOptions.solver_options)
  return p != NULL ? *p : *reinterpret_cast<const ::csmlio::common::proto::CeresSolverOptions*>(
      &::csmlio::common::proto::_CeresSolverOptions_default_instance_);
}
inline ::csmlio::common::proto::CeresSolverOptions* ImuBasedPoseExtrapolatorOptions::mutable_solver_options() {
  
  if (solver_options_ == NULL) {
    solver_options_ = new ::csmlio::common::proto::CeresSolverOptions;
  }
  // @@protoc_insertion_point(field_mutable:cartographer.mapping.proto.ImuBasedPoseExtrapolatorOptions.solver_options)
  return solver_options_;
}
inline ::csmlio::common::proto::CeresSolverOptions* ImuBasedPoseExtrapolatorOptions::release_solver_options() {
  // @@protoc_insertion_point(field_release:cartographer.mapping.proto.ImuBasedPoseExtrapolatorOptions.solver_options)
  
  ::csmlio::common::proto::CeresSolverOptions* temp = solver_options_;
  solver_options_ = NULL;
  return temp;
}
inline void ImuBasedPoseExtrapolatorOptions::set_allocated_solver_options(::csmlio::common::proto::CeresSolverOptions* solver_options) {
  delete solver_options_;
  solver_options_ = solver_options;
  if (solver_options) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:cartographer.mapping.proto.ImuBasedPoseExtrapolatorOptions.solver_options)
}

// double odometry_translation_weight = 8;
inline void ImuBasedPoseExtrapolatorOptions::clear_odometry_translation_weight() {
  odometry_translation_weight_ = 0;
}
inline double ImuBasedPoseExtrapolatorOptions::odometry_translation_weight() const {
  // @@protoc_insertion_point(field_get:cartographer.mapping.proto.ImuBasedPoseExtrapolatorOptions.odometry_translation_weight)
  return odometry_translation_weight_;
}
inline void ImuBasedPoseExtrapolatorOptions::set_odometry_translation_weight(double value) {
  
  odometry_translation_weight_ = value;
  // @@protoc_insertion_point(field_set:cartographer.mapping.proto.ImuBasedPoseExtrapolatorOptions.odometry_translation_weight)
}

// double odometry_rotation_weight = 9;
inline void ImuBasedPoseExtrapolatorOptions::clear_odometry_rotation_weight() {
  odometry_rotation_weight_ = 0;
}
inline double ImuBasedPoseExtrapolatorOptions::odometry_rotation_weight() const {
  // @@protoc_insertion_point(field_get:cartographer.mapping.proto.ImuBasedPoseExtrapolatorOptions.odometry_rotation_weight)
  return odometry_rotation_weight_;
}
inline void ImuBasedPoseExtrapolatorOptions::set_odometry_rotation_weight(double value) {
  
  odometry_rotation_weight_ = value;
  // @@protoc_insertion_point(field_set:cartographer.mapping.proto.ImuBasedPoseExtrapolatorOptions.odometry_rotation_weight)
}

// -------------------------------------------------------------------

// PoseExtrapolatorOptions

// bool use_imu_based = 1;
inline void PoseExtrapolatorOptions::clear_use_imu_based() {
  use_imu_based_ = false;
}
inline bool PoseExtrapolatorOptions::use_imu_based() const {
  // @@protoc_insertion_point(field_get:cartographer.mapping.proto.PoseExtrapolatorOptions.use_imu_based)
  return use_imu_based_;
}
inline void PoseExtrapolatorOptions::set_use_imu_based(bool value) {
  
  use_imu_based_ = value;
  // @@protoc_insertion_point(field_set:cartographer.mapping.proto.PoseExtrapolatorOptions.use_imu_based)
}

// .cartographer.mapping.proto.ConstantVelocityPoseExtrapolatorOptions constant_velocity = 2;
inline bool PoseExtrapolatorOptions::has_constant_velocity() const {
  return this != internal_default_instance() && constant_velocity_ != NULL;
}
inline void PoseExtrapolatorOptions::clear_constant_velocity() {
  if (GetArenaNoVirtual() == NULL && constant_velocity_ != NULL) delete constant_velocity_;
  constant_velocity_ = NULL;
}
inline const ::csmlio::mapping::proto::ConstantVelocityPoseExtrapolatorOptions& PoseExtrapolatorOptions::constant_velocity() const {
  const ::csmlio::mapping::proto::ConstantVelocityPoseExtrapolatorOptions* p = constant_velocity_;
  // @@protoc_insertion_point(field_get:cartographer.mapping.proto.PoseExtrapolatorOptions.constant_velocity)
  return p != NULL ? *p : *reinterpret_cast<const ::csmlio::mapping::proto::ConstantVelocityPoseExtrapolatorOptions*>(
      &::csmlio::mapping::proto::_ConstantVelocityPoseExtrapolatorOptions_default_instance_);
}
inline ::csmlio::mapping::proto::ConstantVelocityPoseExtrapolatorOptions* PoseExtrapolatorOptions::mutable_constant_velocity() {
  
  if (constant_velocity_ == NULL) {
    constant_velocity_ = new ::csmlio::mapping::proto::ConstantVelocityPoseExtrapolatorOptions;
  }
  // @@protoc_insertion_point(field_mutable:cartographer.mapping.proto.PoseExtrapolatorOptions.constant_velocity)
  return constant_velocity_;
}
inline ::csmlio::mapping::proto::ConstantVelocityPoseExtrapolatorOptions* PoseExtrapolatorOptions::release_constant_velocity() {
  // @@protoc_insertion_point(field_release:cartographer.mapping.proto.PoseExtrapolatorOptions.constant_velocity)
  
  ::csmlio::mapping::proto::ConstantVelocityPoseExtrapolatorOptions* temp = constant_velocity_;
  constant_velocity_ = NULL;
  return temp;
}
inline void PoseExtrapolatorOptions::set_allocated_constant_velocity(::csmlio::mapping::proto::ConstantVelocityPoseExtrapolatorOptions* constant_velocity) {
  delete constant_velocity_;
  constant_velocity_ = constant_velocity;
  if (constant_velocity) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:cartographer.mapping.proto.PoseExtrapolatorOptions.constant_velocity)
}

// .cartographer.mapping.proto.ImuBasedPoseExtrapolatorOptions imu_based = 3;
inline bool PoseExtrapolatorOptions::has_imu_based() const {
  return this != internal_default_instance() && imu_based_ != NULL;
}
inline void PoseExtrapolatorOptions::clear_imu_based() {
  if (GetArenaNoVirtual() == NULL && imu_based_ != NULL) delete imu_based_;
  imu_based_ = NULL;
}
inline const ::csmlio::mapping::proto::ImuBasedPoseExtrapolatorOptions& PoseExtrapolatorOptions::imu_based() const {
  const ::csmlio::mapping::proto::ImuBasedPoseExtrapolatorOptions* p = imu_based_;
  // @@protoc_insertion_point(field_get:cartographer.mapping.proto.PoseExtrapolatorOptions.imu_based)
  return p != NULL ? *p : *reinterpret_cast<const ::csmlio::mapping::proto::ImuBasedPoseExtrapolatorOptions*>(
      &::csmlio::mapping::proto::_ImuBasedPoseExtrapolatorOptions_default_instance_);
}
inline ::csmlio::mapping::proto::ImuBasedPoseExtrapolatorOptions* PoseExtrapolatorOptions::mutable_imu_based() {
  
  if (imu_based_ == NULL) {
    imu_based_ = new ::csmlio::mapping::proto::ImuBasedPoseExtrapolatorOptions;
  }
  // @@protoc_insertion_point(field_mutable:cartographer.mapping.proto.PoseExtrapolatorOptions.imu_based)
  return imu_based_;
}
inline ::csmlio::mapping::proto::ImuBasedPoseExtrapolatorOptions* PoseExtrapolatorOptions::release_imu_based() {
  // @@protoc_insertion_point(field_release:cartographer.mapping.proto.PoseExtrapolatorOptions.imu_based)
  
  ::csmlio::mapping::proto::ImuBasedPoseExtrapolatorOptions* temp = imu_based_;
  imu_based_ = NULL;
  return temp;
}
inline void PoseExtrapolatorOptions::set_allocated_imu_based(::csmlio::mapping::proto::ImuBasedPoseExtrapolatorOptions* imu_based) {
  delete imu_based_;
  imu_based_ = imu_based;
  if (imu_based) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:cartographer.mapping.proto.PoseExtrapolatorOptions.imu_based)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


}  // namespace proto
}  // namespace mapping
}  // namespace csmlio

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_cartographer_2fmapping_2fproto_2fpose_5fextrapolator_5foptions_2eproto__INCLUDED
