// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cartographer/mapping/proto/submap.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "csmlio/lio/proto/submap.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace csmlio {
namespace mapping {
namespace proto {
class Submap2DDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<Submap2D>
     _instance;
} _Submap2D_default_instance_;
class Submap3DDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<Submap3D>
     _instance;
} _Submap3D_default_instance_;

namespace protobuf_cartographer_2fmapping_2fproto_2fsubmap_2eproto {


namespace {

::google::protobuf::Metadata file_level_metadata[2];

}  // namespace

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTableField
    const TableStruct::entries[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  {0, 0, 0, ::google::protobuf::internal::kInvalidMask, 0, 0},
};

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::AuxillaryParseTableField
    const TableStruct::aux[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ::google::protobuf::internal::AuxillaryParseTableField(),
};
PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTable const
    TableStruct::schema[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { NULL, NULL, 0, -1, -1, -1, -1, NULL, false },
  { NULL, NULL, 0, -1, -1, -1, -1, NULL, false },
};

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Submap2D, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Submap2D, local_pose_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Submap2D, num_range_data_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Submap2D, finished_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Submap2D, grid_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Submap3D, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Submap3D, local_pose_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Submap3D, num_range_data_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Submap3D, finished_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Submap3D, high_resolution_hybrid_grid_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Submap3D, low_resolution_hybrid_grid_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Submap3D, rotational_scan_matcher_histogram_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(Submap2D)},
  { 9, -1, sizeof(Submap3D)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&_Submap2D_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&_Submap3D_default_instance_),
};

namespace {

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "cartographer/mapping/proto/submap.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 2);
}

}  // namespace
void TableStruct::InitDefaultsImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::InitProtobufDefaults();
  ::csmlio::mapping::proto::protobuf_cartographer_2fmapping_2fproto_2fgrid_5f2d_2eproto::InitDefaults();
  ::csmlio::mapping::proto::protobuf_cartographer_2fmapping_2fproto_2fhybrid_5fgrid_2eproto::InitDefaults();
  ::csmlio::transform::proto::protobuf_cartographer_2ftransform_2fproto_2ftransform_2eproto::InitDefaults();
  _Submap2D_default_instance_._instance.DefaultConstruct();
  ::google::protobuf::internal::OnShutdownDestroyMessage(
      &_Submap2D_default_instance_);_Submap3D_default_instance_._instance.DefaultConstruct();
  ::google::protobuf::internal::OnShutdownDestroyMessage(
      &_Submap3D_default_instance_);_Submap2D_default_instance_._instance.get_mutable()->local_pose_ = const_cast< ::csmlio::transform::proto::Rigid3d*>(
      ::csmlio::transform::proto::Rigid3d::internal_default_instance());
  _Submap2D_default_instance_._instance.get_mutable()->grid_ = const_cast< ::csmlio::mapping::proto::Grid2D*>(
      ::csmlio::mapping::proto::Grid2D::internal_default_instance());
  _Submap3D_default_instance_._instance.get_mutable()->local_pose_ = const_cast< ::csmlio::transform::proto::Rigid3d*>(
      ::csmlio::transform::proto::Rigid3d::internal_default_instance());
  _Submap3D_default_instance_._instance.get_mutable()->high_resolution_hybrid_grid_ = const_cast< ::csmlio::mapping::proto::HybridGrid*>(
      ::csmlio::mapping::proto::HybridGrid::internal_default_instance());
  _Submap3D_default_instance_._instance.get_mutable()->low_resolution_hybrid_grid_ = const_cast< ::csmlio::mapping::proto::HybridGrid*>(
      ::csmlio::mapping::proto::HybridGrid::internal_default_instance());
}

void InitDefaults() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &TableStruct::InitDefaultsImpl);
}
namespace {
void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\'cartographer/mapping/proto/submap.prot"
      "o\022\032cartographer.mapping.proto\032(cartograp"
      "her/mapping/proto/grid_2d.proto\032,cartogr"
      "apher/mapping/proto/hybrid_grid.proto\032,c"
      "artographer/transform/proto/transform.pr"
      "oto\"\241\001\n\010Submap2D\0229\n\nlocal_pose\030\001 \001(\0132%.c"
      "artographer.transform.proto.Rigid3d\022\026\n\016n"
      "um_range_data\030\002 \001(\005\022\020\n\010finished\030\003 \001(\010\0220\n"
      "\004grid\030\004 \001(\0132\".cartographer.mapping.proto"
      ".Grid2D\"\263\002\n\010Submap3D\0229\n\nlocal_pose\030\001 \001(\013"
      "2%.cartographer.transform.proto.Rigid3d\022"
      "\026\n\016num_range_data\030\002 \001(\005\022\020\n\010finished\030\003 \001("
      "\010\022K\n\033high_resolution_hybrid_grid\030\004 \001(\0132&"
      ".cartographer.mapping.proto.HybridGrid\022J"
      "\n\032low_resolution_hybrid_grid\030\005 \001(\0132&.car"
      "tographer.mapping.proto.HybridGrid\022)\n!ro"
      "tational_scan_matcher_histogram\030\006 \003(\002b\006p"
      "roto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 685);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "cartographer/mapping/proto/submap.proto", &protobuf_RegisterTypes);
  ::csmlio::mapping::proto::protobuf_cartographer_2fmapping_2fproto_2fgrid_5f2d_2eproto::AddDescriptors();
  ::csmlio::mapping::proto::protobuf_cartographer_2fmapping_2fproto_2fhybrid_5fgrid_2eproto::AddDescriptors();
  ::csmlio::transform::proto::protobuf_cartographer_2ftransform_2fproto_2ftransform_2eproto::AddDescriptors();
}
} // anonymous namespace

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;

}  // namespace protobuf_cartographer_2fmapping_2fproto_2fsubmap_2eproto


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Submap2D::kLocalPoseFieldNumber;
const int Submap2D::kNumRangeDataFieldNumber;
const int Submap2D::kFinishedFieldNumber;
const int Submap2D::kGridFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Submap2D::Submap2D()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_cartographer_2fmapping_2fproto_2fsubmap_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:cartographer.mapping.proto.Submap2D)
}
Submap2D::Submap2D(const Submap2D& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.has_local_pose()) {
    local_pose_ = new ::csmlio::transform::proto::Rigid3d(*from.local_pose_);
  } else {
    local_pose_ = NULL;
  }
  if (from.has_grid()) {
    grid_ = new ::csmlio::mapping::proto::Grid2D(*from.grid_);
  } else {
    grid_ = NULL;
  }
  ::memcpy(&num_range_data_, &from.num_range_data_,
    static_cast<size_t>(reinterpret_cast<char*>(&finished_) -
    reinterpret_cast<char*>(&num_range_data_)) + sizeof(finished_));
  // @@protoc_insertion_point(copy_constructor:cartographer.mapping.proto.Submap2D)
}

void Submap2D::SharedCtor() {
  ::memset(&local_pose_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&finished_) -
      reinterpret_cast<char*>(&local_pose_)) + sizeof(finished_));
  _cached_size_ = 0;
}

Submap2D::~Submap2D() {
  // @@protoc_insertion_point(destructor:cartographer.mapping.proto.Submap2D)
  SharedDtor();
}

void Submap2D::SharedDtor() {
  if (this != internal_default_instance()) delete local_pose_;
  if (this != internal_default_instance()) delete grid_;
}

void Submap2D::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Submap2D::descriptor() {
  protobuf_cartographer_2fmapping_2fproto_2fsubmap_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_cartographer_2fmapping_2fproto_2fsubmap_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const Submap2D& Submap2D::default_instance() {
  protobuf_cartographer_2fmapping_2fproto_2fsubmap_2eproto::InitDefaults();
  return *internal_default_instance();
}

Submap2D* Submap2D::New(::google::protobuf::Arena* arena) const {
  Submap2D* n = new Submap2D;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Submap2D::Clear() {
// @@protoc_insertion_point(message_clear_start:cartographer.mapping.proto.Submap2D)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaNoVirtual() == NULL && local_pose_ != NULL) {
    delete local_pose_;
  }
  local_pose_ = NULL;
  if (GetArenaNoVirtual() == NULL && grid_ != NULL) {
    delete grid_;
  }
  grid_ = NULL;
  ::memset(&num_range_data_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&finished_) -
      reinterpret_cast<char*>(&num_range_data_)) + sizeof(finished_));
  _internal_metadata_.Clear();
}

bool Submap2D::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:cartographer.mapping.proto.Submap2D)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // .cartographer.transform.proto.Rigid3d local_pose = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_local_pose()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 num_range_data = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &num_range_data_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bool finished = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u /* 24 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &finished_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .cartographer.mapping.proto.Grid2D grid = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(34u /* 34 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_grid()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:cartographer.mapping.proto.Submap2D)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:cartographer.mapping.proto.Submap2D)
  return false;
#undef DO_
}

void Submap2D::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:cartographer.mapping.proto.Submap2D)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .cartographer.transform.proto.Rigid3d local_pose = 1;
  if (this->has_local_pose()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, *this->local_pose_, output);
  }

  // int32 num_range_data = 2;
  if (this->num_range_data() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->num_range_data(), output);
  }

  // bool finished = 3;
  if (this->finished() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(3, this->finished(), output);
  }

  // .cartographer.mapping.proto.Grid2D grid = 4;
  if (this->has_grid()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      4, *this->grid_, output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:cartographer.mapping.proto.Submap2D)
}

::google::protobuf::uint8* Submap2D::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:cartographer.mapping.proto.Submap2D)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .cartographer.transform.proto.Rigid3d local_pose = 1;
  if (this->has_local_pose()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        1, *this->local_pose_, deterministic, target);
  }

  // int32 num_range_data = 2;
  if (this->num_range_data() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->num_range_data(), target);
  }

  // bool finished = 3;
  if (this->finished() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(3, this->finished(), target);
  }

  // .cartographer.mapping.proto.Grid2D grid = 4;
  if (this->has_grid()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        4, *this->grid_, deterministic, target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:cartographer.mapping.proto.Submap2D)
  return target;
}

size_t Submap2D::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:cartographer.mapping.proto.Submap2D)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // .cartographer.transform.proto.Rigid3d local_pose = 1;
  if (this->has_local_pose()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->local_pose_);
  }

  // .cartographer.mapping.proto.Grid2D grid = 4;
  if (this->has_grid()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->grid_);
  }

  // int32 num_range_data = 2;
  if (this->num_range_data() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->num_range_data());
  }

  // bool finished = 3;
  if (this->finished() != 0) {
    total_size += 1 + 1;
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Submap2D::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:cartographer.mapping.proto.Submap2D)
  GOOGLE_DCHECK_NE(&from, this);
  const Submap2D* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const Submap2D>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:cartographer.mapping.proto.Submap2D)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:cartographer.mapping.proto.Submap2D)
    MergeFrom(*source);
  }
}

void Submap2D::MergeFrom(const Submap2D& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:cartographer.mapping.proto.Submap2D)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.has_local_pose()) {
    mutable_local_pose()->::csmlio::transform::proto::Rigid3d::MergeFrom(from.local_pose());
  }
  if (from.has_grid()) {
    mutable_grid()->::csmlio::mapping::proto::Grid2D::MergeFrom(from.grid());
  }
  if (from.num_range_data() != 0) {
    set_num_range_data(from.num_range_data());
  }
  if (from.finished() != 0) {
    set_finished(from.finished());
  }
}

void Submap2D::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:cartographer.mapping.proto.Submap2D)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Submap2D::CopyFrom(const Submap2D& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:cartographer.mapping.proto.Submap2D)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Submap2D::IsInitialized() const {
  return true;
}

void Submap2D::Swap(Submap2D* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Submap2D::InternalSwap(Submap2D* other) {
  using std::swap;
  swap(local_pose_, other->local_pose_);
  swap(grid_, other->grid_);
  swap(num_range_data_, other->num_range_data_);
  swap(finished_, other->finished_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata Submap2D::GetMetadata() const {
  protobuf_cartographer_2fmapping_2fproto_2fsubmap_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_cartographer_2fmapping_2fproto_2fsubmap_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// Submap2D

// .cartographer.transform.proto.Rigid3d local_pose = 1;
bool Submap2D::has_local_pose() const {
  return this != internal_default_instance() && local_pose_ != NULL;
}
void Submap2D::clear_local_pose() {
  if (GetArenaNoVirtual() == NULL && local_pose_ != NULL) delete local_pose_;
  local_pose_ = NULL;
}
const ::csmlio::transform::proto::Rigid3d& Submap2D::local_pose() const {
  const ::csmlio::transform::proto::Rigid3d* p = local_pose_;
  // @@protoc_insertion_point(field_get:cartographer.mapping.proto.Submap2D.local_pose)
  return p != NULL ? *p : *reinterpret_cast<const ::csmlio::transform::proto::Rigid3d*>(
      &::csmlio::transform::proto::_Rigid3d_default_instance_);
}
::csmlio::transform::proto::Rigid3d* Submap2D::mutable_local_pose() {
  
  if (local_pose_ == NULL) {
    local_pose_ = new ::csmlio::transform::proto::Rigid3d;
  }
  // @@protoc_insertion_point(field_mutable:cartographer.mapping.proto.Submap2D.local_pose)
  return local_pose_;
}
::csmlio::transform::proto::Rigid3d* Submap2D::release_local_pose() {
  // @@protoc_insertion_point(field_release:cartographer.mapping.proto.Submap2D.local_pose)
  
  ::csmlio::transform::proto::Rigid3d* temp = local_pose_;
  local_pose_ = NULL;
  return temp;
}
void Submap2D::set_allocated_local_pose(::csmlio::transform::proto::Rigid3d* local_pose) {
  delete local_pose_;
  local_pose_ = local_pose;
  if (local_pose) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:cartographer.mapping.proto.Submap2D.local_pose)
}

// int32 num_range_data = 2;
void Submap2D::clear_num_range_data() {
  num_range_data_ = 0;
}
::google::protobuf::int32 Submap2D::num_range_data() const {
  // @@protoc_insertion_point(field_get:cartographer.mapping.proto.Submap2D.num_range_data)
  return num_range_data_;
}
void Submap2D::set_num_range_data(::google::protobuf::int32 value) {
  
  num_range_data_ = value;
  // @@protoc_insertion_point(field_set:cartographer.mapping.proto.Submap2D.num_range_data)
}

// bool finished = 3;
void Submap2D::clear_finished() {
  finished_ = false;
}
bool Submap2D::finished() const {
  // @@protoc_insertion_point(field_get:cartographer.mapping.proto.Submap2D.finished)
  return finished_;
}
void Submap2D::set_finished(bool value) {
  
  finished_ = value;
  // @@protoc_insertion_point(field_set:cartographer.mapping.proto.Submap2D.finished)
}

// .cartographer.mapping.proto.Grid2D grid = 4;
bool Submap2D::has_grid() const {
  return this != internal_default_instance() && grid_ != NULL;
}
void Submap2D::clear_grid() {
  if (GetArenaNoVirtual() == NULL && grid_ != NULL) delete grid_;
  grid_ = NULL;
}
const ::csmlio::mapping::proto::Grid2D& Submap2D::grid() const {
  const ::csmlio::mapping::proto::Grid2D* p = grid_;
  // @@protoc_insertion_point(field_get:cartographer.mapping.proto.Submap2D.grid)
  return p != NULL ? *p : *reinterpret_cast<const ::csmlio::mapping::proto::Grid2D*>(
      &::csmlio::mapping::proto::_Grid2D_default_instance_);
}
::csmlio::mapping::proto::Grid2D* Submap2D::mutable_grid() {
  
  if (grid_ == NULL) {
    grid_ = new ::csmlio::mapping::proto::Grid2D;
  }
  // @@protoc_insertion_point(field_mutable:cartographer.mapping.proto.Submap2D.grid)
  return grid_;
}
::csmlio::mapping::proto::Grid2D* Submap2D::release_grid() {
  // @@protoc_insertion_point(field_release:cartographer.mapping.proto.Submap2D.grid)
  
  ::csmlio::mapping::proto::Grid2D* temp = grid_;
  grid_ = NULL;
  return temp;
}
void Submap2D::set_allocated_grid(::csmlio::mapping::proto::Grid2D* grid) {
  delete grid_;
  grid_ = grid;
  if (grid) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:cartographer.mapping.proto.Submap2D.grid)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Submap3D::kLocalPoseFieldNumber;
const int Submap3D::kNumRangeDataFieldNumber;
const int Submap3D::kFinishedFieldNumber;
const int Submap3D::kHighResolutionHybridGridFieldNumber;
const int Submap3D::kLowResolutionHybridGridFieldNumber;
const int Submap3D::kRotationalScanMatcherHistogramFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Submap3D::Submap3D()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_cartographer_2fmapping_2fproto_2fsubmap_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:cartographer.mapping.proto.Submap3D)
}
Submap3D::Submap3D(const Submap3D& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      rotational_scan_matcher_histogram_(from.rotational_scan_matcher_histogram_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.has_local_pose()) {
    local_pose_ = new ::csmlio::transform::proto::Rigid3d(*from.local_pose_);
  } else {
    local_pose_ = NULL;
  }
  if (from.has_high_resolution_hybrid_grid()) {
    high_resolution_hybrid_grid_ = new ::csmlio::mapping::proto::HybridGrid(*from.high_resolution_hybrid_grid_);
  } else {
    high_resolution_hybrid_grid_ = NULL;
  }
  if (from.has_low_resolution_hybrid_grid()) {
    low_resolution_hybrid_grid_ = new ::csmlio::mapping::proto::HybridGrid(*from.low_resolution_hybrid_grid_);
  } else {
    low_resolution_hybrid_grid_ = NULL;
  }
  ::memcpy(&num_range_data_, &from.num_range_data_,
    static_cast<size_t>(reinterpret_cast<char*>(&finished_) -
    reinterpret_cast<char*>(&num_range_data_)) + sizeof(finished_));
  // @@protoc_insertion_point(copy_constructor:cartographer.mapping.proto.Submap3D)
}

void Submap3D::SharedCtor() {
  ::memset(&local_pose_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&finished_) -
      reinterpret_cast<char*>(&local_pose_)) + sizeof(finished_));
  _cached_size_ = 0;
}

Submap3D::~Submap3D() {
  // @@protoc_insertion_point(destructor:cartographer.mapping.proto.Submap3D)
  SharedDtor();
}

void Submap3D::SharedDtor() {
  if (this != internal_default_instance()) delete local_pose_;
  if (this != internal_default_instance()) delete high_resolution_hybrid_grid_;
  if (this != internal_default_instance()) delete low_resolution_hybrid_grid_;
}

void Submap3D::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Submap3D::descriptor() {
  protobuf_cartographer_2fmapping_2fproto_2fsubmap_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_cartographer_2fmapping_2fproto_2fsubmap_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const Submap3D& Submap3D::default_instance() {
  protobuf_cartographer_2fmapping_2fproto_2fsubmap_2eproto::InitDefaults();
  return *internal_default_instance();
}

Submap3D* Submap3D::New(::google::protobuf::Arena* arena) const {
  Submap3D* n = new Submap3D;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Submap3D::Clear() {
// @@protoc_insertion_point(message_clear_start:cartographer.mapping.proto.Submap3D)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  rotational_scan_matcher_histogram_.Clear();
  if (GetArenaNoVirtual() == NULL && local_pose_ != NULL) {
    delete local_pose_;
  }
  local_pose_ = NULL;
  if (GetArenaNoVirtual() == NULL && high_resolution_hybrid_grid_ != NULL) {
    delete high_resolution_hybrid_grid_;
  }
  high_resolution_hybrid_grid_ = NULL;
  if (GetArenaNoVirtual() == NULL && low_resolution_hybrid_grid_ != NULL) {
    delete low_resolution_hybrid_grid_;
  }
  low_resolution_hybrid_grid_ = NULL;
  ::memset(&num_range_data_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&finished_) -
      reinterpret_cast<char*>(&num_range_data_)) + sizeof(finished_));
  _internal_metadata_.Clear();
}

bool Submap3D::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:cartographer.mapping.proto.Submap3D)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // .cartographer.transform.proto.Rigid3d local_pose = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_local_pose()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 num_range_data = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &num_range_data_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bool finished = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u /* 24 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &finished_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .cartographer.mapping.proto.HybridGrid high_resolution_hybrid_grid = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(34u /* 34 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_high_resolution_hybrid_grid()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .cartographer.mapping.proto.HybridGrid low_resolution_hybrid_grid = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(42u /* 42 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_low_resolution_hybrid_grid()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated float rotational_scan_matcher_histogram = 6;
      case 6: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(50u /* 50 & 0xFF */)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, this->mutable_rotational_scan_matcher_histogram())));
        } else if (
            static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(53u /* 53 & 0xFF */)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitiveNoInline<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 1, 50u, input, this->mutable_rotational_scan_matcher_histogram())));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:cartographer.mapping.proto.Submap3D)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:cartographer.mapping.proto.Submap3D)
  return false;
#undef DO_
}

void Submap3D::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:cartographer.mapping.proto.Submap3D)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .cartographer.transform.proto.Rigid3d local_pose = 1;
  if (this->has_local_pose()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, *this->local_pose_, output);
  }

  // int32 num_range_data = 2;
  if (this->num_range_data() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->num_range_data(), output);
  }

  // bool finished = 3;
  if (this->finished() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(3, this->finished(), output);
  }

  // .cartographer.mapping.proto.HybridGrid high_resolution_hybrid_grid = 4;
  if (this->has_high_resolution_hybrid_grid()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      4, *this->high_resolution_hybrid_grid_, output);
  }

  // .cartographer.mapping.proto.HybridGrid low_resolution_hybrid_grid = 5;
  if (this->has_low_resolution_hybrid_grid()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      5, *this->low_resolution_hybrid_grid_, output);
  }

  // repeated float rotational_scan_matcher_histogram = 6;
  if (this->rotational_scan_matcher_histogram_size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteTag(6, ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED, output);
    output->WriteVarint32(static_cast< ::google::protobuf::uint32>(
        _rotational_scan_matcher_histogram_cached_byte_size_));
    ::google::protobuf::internal::WireFormatLite::WriteFloatArray(
      this->rotational_scan_matcher_histogram().data(), this->rotational_scan_matcher_histogram_size(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:cartographer.mapping.proto.Submap3D)
}

::google::protobuf::uint8* Submap3D::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:cartographer.mapping.proto.Submap3D)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .cartographer.transform.proto.Rigid3d local_pose = 1;
  if (this->has_local_pose()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        1, *this->local_pose_, deterministic, target);
  }

  // int32 num_range_data = 2;
  if (this->num_range_data() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->num_range_data(), target);
  }

  // bool finished = 3;
  if (this->finished() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(3, this->finished(), target);
  }

  // .cartographer.mapping.proto.HybridGrid high_resolution_hybrid_grid = 4;
  if (this->has_high_resolution_hybrid_grid()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        4, *this->high_resolution_hybrid_grid_, deterministic, target);
  }

  // .cartographer.mapping.proto.HybridGrid low_resolution_hybrid_grid = 5;
  if (this->has_low_resolution_hybrid_grid()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        5, *this->low_resolution_hybrid_grid_, deterministic, target);
  }

  // repeated float rotational_scan_matcher_histogram = 6;
  if (this->rotational_scan_matcher_histogram_size() > 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteTagToArray(
      6,
      ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED,
      target);
    target = ::google::protobuf::io::CodedOutputStream::WriteVarint32ToArray(
        static_cast< ::google::protobuf::uint32>(
            _rotational_scan_matcher_histogram_cached_byte_size_), target);
    target = ::google::protobuf::internal::WireFormatLite::
      WriteFloatNoTagToArray(this->rotational_scan_matcher_histogram_, target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:cartographer.mapping.proto.Submap3D)
  return target;
}

size_t Submap3D::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:cartographer.mapping.proto.Submap3D)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // repeated float rotational_scan_matcher_histogram = 6;
  {
    unsigned int count = static_cast<unsigned int>(this->rotational_scan_matcher_histogram_size());
    size_t data_size = 4UL * count;
    if (data_size > 0) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
            static_cast< ::google::protobuf::int32>(data_size));
    }
    int cached_size = ::google::protobuf::internal::ToCachedSize(data_size);
    GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
    _rotational_scan_matcher_histogram_cached_byte_size_ = cached_size;
    GOOGLE_SAFE_CONCURRENT_WRITES_END();
    total_size += data_size;
  }

  // .cartographer.transform.proto.Rigid3d local_pose = 1;
  if (this->has_local_pose()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->local_pose_);
  }

  // .cartographer.mapping.proto.HybridGrid high_resolution_hybrid_grid = 4;
  if (this->has_high_resolution_hybrid_grid()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->high_resolution_hybrid_grid_);
  }

  // .cartographer.mapping.proto.HybridGrid low_resolution_hybrid_grid = 5;
  if (this->has_low_resolution_hybrid_grid()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->low_resolution_hybrid_grid_);
  }

  // int32 num_range_data = 2;
  if (this->num_range_data() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->num_range_data());
  }

  // bool finished = 3;
  if (this->finished() != 0) {
    total_size += 1 + 1;
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Submap3D::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:cartographer.mapping.proto.Submap3D)
  GOOGLE_DCHECK_NE(&from, this);
  const Submap3D* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const Submap3D>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:cartographer.mapping.proto.Submap3D)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:cartographer.mapping.proto.Submap3D)
    MergeFrom(*source);
  }
}

void Submap3D::MergeFrom(const Submap3D& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:cartographer.mapping.proto.Submap3D)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  rotational_scan_matcher_histogram_.MergeFrom(from.rotational_scan_matcher_histogram_);
  if (from.has_local_pose()) {
    mutable_local_pose()->::csmlio::transform::proto::Rigid3d::MergeFrom(from.local_pose());
  }
  if (from.has_high_resolution_hybrid_grid()) {
    mutable_high_resolution_hybrid_grid()->::csmlio::mapping::proto::HybridGrid::MergeFrom(from.high_resolution_hybrid_grid());
  }
  if (from.has_low_resolution_hybrid_grid()) {
    mutable_low_resolution_hybrid_grid()->::csmlio::mapping::proto::HybridGrid::MergeFrom(from.low_resolution_hybrid_grid());
  }
  if (from.num_range_data() != 0) {
    set_num_range_data(from.num_range_data());
  }
  if (from.finished() != 0) {
    set_finished(from.finished());
  }
}

void Submap3D::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:cartographer.mapping.proto.Submap3D)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Submap3D::CopyFrom(const Submap3D& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:cartographer.mapping.proto.Submap3D)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Submap3D::IsInitialized() const {
  return true;
}

void Submap3D::Swap(Submap3D* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Submap3D::InternalSwap(Submap3D* other) {
  using std::swap;
  rotational_scan_matcher_histogram_.InternalSwap(&other->rotational_scan_matcher_histogram_);
  swap(local_pose_, other->local_pose_);
  swap(high_resolution_hybrid_grid_, other->high_resolution_hybrid_grid_);
  swap(low_resolution_hybrid_grid_, other->low_resolution_hybrid_grid_);
  swap(num_range_data_, other->num_range_data_);
  swap(finished_, other->finished_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata Submap3D::GetMetadata() const {
  protobuf_cartographer_2fmapping_2fproto_2fsubmap_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_cartographer_2fmapping_2fproto_2fsubmap_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// Submap3D

// .cartographer.transform.proto.Rigid3d local_pose = 1;
bool Submap3D::has_local_pose() const {
  return this != internal_default_instance() && local_pose_ != NULL;
}
void Submap3D::clear_local_pose() {
  if (GetArenaNoVirtual() == NULL && local_pose_ != NULL) delete local_pose_;
  local_pose_ = NULL;
}
const ::csmlio::transform::proto::Rigid3d& Submap3D::local_pose() const {
  const ::csmlio::transform::proto::Rigid3d* p = local_pose_;
  // @@protoc_insertion_point(field_get:cartographer.mapping.proto.Submap3D.local_pose)
  return p != NULL ? *p : *reinterpret_cast<const ::csmlio::transform::proto::Rigid3d*>(
      &::csmlio::transform::proto::_Rigid3d_default_instance_);
}
::csmlio::transform::proto::Rigid3d* Submap3D::mutable_local_pose() {
  
  if (local_pose_ == NULL) {
    local_pose_ = new ::csmlio::transform::proto::Rigid3d;
  }
  // @@protoc_insertion_point(field_mutable:cartographer.mapping.proto.Submap3D.local_pose)
  return local_pose_;
}
::csmlio::transform::proto::Rigid3d* Submap3D::release_local_pose() {
  // @@protoc_insertion_point(field_release:cartographer.mapping.proto.Submap3D.local_pose)
  
  ::csmlio::transform::proto::Rigid3d* temp = local_pose_;
  local_pose_ = NULL;
  return temp;
}
void Submap3D::set_allocated_local_pose(::csmlio::transform::proto::Rigid3d* local_pose) {
  delete local_pose_;
  local_pose_ = local_pose;
  if (local_pose) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:cartographer.mapping.proto.Submap3D.local_pose)
}

// int32 num_range_data = 2;
void Submap3D::clear_num_range_data() {
  num_range_data_ = 0;
}
::google::protobuf::int32 Submap3D::num_range_data() const {
  // @@protoc_insertion_point(field_get:cartographer.mapping.proto.Submap3D.num_range_data)
  return num_range_data_;
}
void Submap3D::set_num_range_data(::google::protobuf::int32 value) {
  
  num_range_data_ = value;
  // @@protoc_insertion_point(field_set:cartographer.mapping.proto.Submap3D.num_range_data)
}

// bool finished = 3;
void Submap3D::clear_finished() {
  finished_ = false;
}
bool Submap3D::finished() const {
  // @@protoc_insertion_point(field_get:cartographer.mapping.proto.Submap3D.finished)
  return finished_;
}
void Submap3D::set_finished(bool value) {
  
  finished_ = value;
  // @@protoc_insertion_point(field_set:cartographer.mapping.proto.Submap3D.finished)
}

// .cartographer.mapping.proto.HybridGrid high_resolution_hybrid_grid = 4;
bool Submap3D::has_high_resolution_hybrid_grid() const {
  return this != internal_default_instance() && high_resolution_hybrid_grid_ != NULL;
}
void Submap3D::clear_high_resolution_hybrid_grid() {
  if (GetArenaNoVirtual() == NULL && high_resolution_hybrid_grid_ != NULL) delete high_resolution_hybrid_grid_;
  high_resolution_hybrid_grid_ = NULL;
}
const ::csmlio::mapping::proto::HybridGrid& Submap3D::high_resolution_hybrid_grid() const {
  const ::csmlio::mapping::proto::HybridGrid* p = high_resolution_hybrid_grid_;
  // @@protoc_insertion_point(field_get:cartographer.mapping.proto.Submap3D.high_resolution_hybrid_grid)
  return p != NULL ? *p : *reinterpret_cast<const ::csmlio::mapping::proto::HybridGrid*>(
      &::csmlio::mapping::proto::_HybridGrid_default_instance_);
}
::csmlio::mapping::proto::HybridGrid* Submap3D::mutable_high_resolution_hybrid_grid() {
  
  if (high_resolution_hybrid_grid_ == NULL) {
    high_resolution_hybrid_grid_ = new ::csmlio::mapping::proto::HybridGrid;
  }
  // @@protoc_insertion_point(field_mutable:cartographer.mapping.proto.Submap3D.high_resolution_hybrid_grid)
  return high_resolution_hybrid_grid_;
}
::csmlio::mapping::proto::HybridGrid* Submap3D::release_high_resolution_hybrid_grid() {
  // @@protoc_insertion_point(field_release:cartographer.mapping.proto.Submap3D.high_resolution_hybrid_grid)
  
  ::csmlio::mapping::proto::HybridGrid* temp = high_resolution_hybrid_grid_;
  high_resolution_hybrid_grid_ = NULL;
  return temp;
}
void Submap3D::set_allocated_high_resolution_hybrid_grid(::csmlio::mapping::proto::HybridGrid* high_resolution_hybrid_grid) {
  delete high_resolution_hybrid_grid_;
  high_resolution_hybrid_grid_ = high_resolution_hybrid_grid;
  if (high_resolution_hybrid_grid) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:cartographer.mapping.proto.Submap3D.high_resolution_hybrid_grid)
}

// .cartographer.mapping.proto.HybridGrid low_resolution_hybrid_grid = 5;
bool Submap3D::has_low_resolution_hybrid_grid() const {
  return this != internal_default_instance() && low_resolution_hybrid_grid_ != NULL;
}
void Submap3D::clear_low_resolution_hybrid_grid() {
  if (GetArenaNoVirtual() == NULL && low_resolution_hybrid_grid_ != NULL) delete low_resolution_hybrid_grid_;
  low_resolution_hybrid_grid_ = NULL;
}
const ::csmlio::mapping::proto::HybridGrid& Submap3D::low_resolution_hybrid_grid() const {
  const ::csmlio::mapping::proto::HybridGrid* p = low_resolution_hybrid_grid_;
  // @@protoc_insertion_point(field_get:cartographer.mapping.proto.Submap3D.low_resolution_hybrid_grid)
  return p != NULL ? *p : *reinterpret_cast<const ::csmlio::mapping::proto::HybridGrid*>(
      &::csmlio::mapping::proto::_HybridGrid_default_instance_);
}
::csmlio::mapping::proto::HybridGrid* Submap3D::mutable_low_resolution_hybrid_grid() {
  
  if (low_resolution_hybrid_grid_ == NULL) {
    low_resolution_hybrid_grid_ = new ::csmlio::mapping::proto::HybridGrid;
  }
  // @@protoc_insertion_point(field_mutable:cartographer.mapping.proto.Submap3D.low_resolution_hybrid_grid)
  return low_resolution_hybrid_grid_;
}
::csmlio::mapping::proto::HybridGrid* Submap3D::release_low_resolution_hybrid_grid() {
  // @@protoc_insertion_point(field_release:cartographer.mapping.proto.Submap3D.low_resolution_hybrid_grid)
  
  ::csmlio::mapping::proto::HybridGrid* temp = low_resolution_hybrid_grid_;
  low_resolution_hybrid_grid_ = NULL;
  return temp;
}
void Submap3D::set_allocated_low_resolution_hybrid_grid(::csmlio::mapping::proto::HybridGrid* low_resolution_hybrid_grid) {
  delete low_resolution_hybrid_grid_;
  low_resolution_hybrid_grid_ = low_resolution_hybrid_grid;
  if (low_resolution_hybrid_grid) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:cartographer.mapping.proto.Submap3D.low_resolution_hybrid_grid)
}

// repeated float rotational_scan_matcher_histogram = 6;
int Submap3D::rotational_scan_matcher_histogram_size() const {
  return rotational_scan_matcher_histogram_.size();
}
void Submap3D::clear_rotational_scan_matcher_histogram() {
  rotational_scan_matcher_histogram_.Clear();
}
float Submap3D::rotational_scan_matcher_histogram(int index) const {
  // @@protoc_insertion_point(field_get:cartographer.mapping.proto.Submap3D.rotational_scan_matcher_histogram)
  return rotational_scan_matcher_histogram_.Get(index);
}
void Submap3D::set_rotational_scan_matcher_histogram(int index, float value) {
  rotational_scan_matcher_histogram_.Set(index, value);
  // @@protoc_insertion_point(field_set:cartographer.mapping.proto.Submap3D.rotational_scan_matcher_histogram)
}
void Submap3D::add_rotational_scan_matcher_histogram(float value) {
  rotational_scan_matcher_histogram_.Add(value);
  // @@protoc_insertion_point(field_add:cartographer.mapping.proto.Submap3D.rotational_scan_matcher_histogram)
}
const ::google::protobuf::RepeatedField< float >&
Submap3D::rotational_scan_matcher_histogram() const {
  // @@protoc_insertion_point(field_list:cartographer.mapping.proto.Submap3D.rotational_scan_matcher_histogram)
  return rotational_scan_matcher_histogram_;
}
::google::protobuf::RepeatedField< float >*
Submap3D::mutable_rotational_scan_matcher_histogram() {
  // @@protoc_insertion_point(field_mutable_list:cartographer.mapping.proto.Submap3D.rotational_scan_matcher_histogram)
  return &rotational_scan_matcher_histogram_;
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace proto
}  // namespace mapping
}  // namespace csmlio

// @@protoc_insertion_point(global_scope)
