// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cartographer/mapping/proto/tsdf_range_data_inserter_options_2d.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "csmlio/lio/proto/tsdf_range_data_inserter_options_2d.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace csmlio {
namespace mapping {
namespace proto {
class TSDFRangeDataInserterOptions2DDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<TSDFRangeDataInserterOptions2D>
     _instance;
} _TSDFRangeDataInserterOptions2D_default_instance_;

namespace protobuf_cartographer_2fmapping_2fproto_2ftsdf_5frange_5fdata_5finserter_5foptions_5f2d_2eproto {


namespace {

::google::protobuf::Metadata file_level_metadata[1];

}  // namespace

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTableField
    const TableStruct::entries[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  {0, 0, 0, ::google::protobuf::internal::kInvalidMask, 0, 0},
};

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::AuxillaryParseTableField
    const TableStruct::aux[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ::google::protobuf::internal::AuxillaryParseTableField(),
};
PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTable const
    TableStruct::schema[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { NULL, NULL, 0, -1, -1, -1, -1, NULL, false },
};

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TSDFRangeDataInserterOptions2D, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TSDFRangeDataInserterOptions2D, truncation_distance_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TSDFRangeDataInserterOptions2D, maximum_weight_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TSDFRangeDataInserterOptions2D, update_free_space_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TSDFRangeDataInserterOptions2D, normal_estimation_options_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TSDFRangeDataInserterOptions2D, project_sdf_distance_to_scan_normal_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TSDFRangeDataInserterOptions2D, update_weight_range_exponent_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TSDFRangeDataInserterOptions2D, update_weight_angle_scan_normal_to_ray_kernel_bandwidth_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TSDFRangeDataInserterOptions2D, update_weight_distance_cell_to_hit_kernel_bandwidth_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(TSDFRangeDataInserterOptions2D)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&_TSDFRangeDataInserterOptions2D_default_instance_),
};

namespace {

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "cartographer/mapping/proto/tsdf_range_data_inserter_options_2d.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

}  // namespace
void TableStruct::InitDefaultsImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::InitProtobufDefaults();
  ::csmlio::mapping::proto::protobuf_cartographer_2fmapping_2fproto_2fnormal_5festimation_5foptions_5f2d_2eproto::InitDefaults();
  _TSDFRangeDataInserterOptions2D_default_instance_._instance.DefaultConstruct();
  ::google::protobuf::internal::OnShutdownDestroyMessage(
      &_TSDFRangeDataInserterOptions2D_default_instance_);_TSDFRangeDataInserterOptions2D_default_instance_._instance.get_mutable()->normal_estimation_options_ = const_cast< ::csmlio::mapping::proto::NormalEstimationOptions2D*>(
      ::csmlio::mapping::proto::NormalEstimationOptions2D::internal_default_instance());
}

void InitDefaults() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &TableStruct::InitDefaultsImpl);
}
namespace {
void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\nDcartographer/mapping/proto/tsdf_range_"
      "data_inserter_options_2d.proto\022\032cartogra"
      "pher.mapping.proto\032=cartographer/mapping"
      "/proto/normal_estimation_options_2d.prot"
      "o\"\233\003\n\036TSDFRangeDataInserterOptions2D\022\033\n\023"
      "truncation_distance\030\001 \001(\001\022\026\n\016maximum_wei"
      "ght\030\002 \001(\001\022\031\n\021update_free_space\030\003 \001(\010\022X\n\031"
      "normal_estimation_options\030\004 \001(\01325.cartog"
      "rapher.mapping.proto.NormalEstimationOpt"
      "ions2D\022+\n#project_sdf_distance_to_scan_n"
      "ormal\030\005 \001(\010\022$\n\034update_weight_range_expon"
      "ent\030\006 \001(\005\022\?\n7update_weight_angle_scan_no"
      "rmal_to_ray_kernel_bandwidth\030\007 \001(\001\022;\n3up"
      "date_weight_distance_cell_to_hit_kernel_"
      "bandwidth\030\010 \001(\001b\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 583);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "cartographer/mapping/proto/tsdf_range_data_inserter_options_2d.proto", &protobuf_RegisterTypes);
  ::csmlio::mapping::proto::protobuf_cartographer_2fmapping_2fproto_2fnormal_5festimation_5foptions_5f2d_2eproto::AddDescriptors();
}
} // anonymous namespace

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;

}  // namespace protobuf_cartographer_2fmapping_2fproto_2ftsdf_5frange_5fdata_5finserter_5foptions_5f2d_2eproto


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int TSDFRangeDataInserterOptions2D::kTruncationDistanceFieldNumber;
const int TSDFRangeDataInserterOptions2D::kMaximumWeightFieldNumber;
const int TSDFRangeDataInserterOptions2D::kUpdateFreeSpaceFieldNumber;
const int TSDFRangeDataInserterOptions2D::kNormalEstimationOptionsFieldNumber;
const int TSDFRangeDataInserterOptions2D::kProjectSdfDistanceToScanNormalFieldNumber;
const int TSDFRangeDataInserterOptions2D::kUpdateWeightRangeExponentFieldNumber;
const int TSDFRangeDataInserterOptions2D::kUpdateWeightAngleScanNormalToRayKernelBandwidthFieldNumber;
const int TSDFRangeDataInserterOptions2D::kUpdateWeightDistanceCellToHitKernelBandwidthFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

TSDFRangeDataInserterOptions2D::TSDFRangeDataInserterOptions2D()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_cartographer_2fmapping_2fproto_2ftsdf_5frange_5fdata_5finserter_5foptions_5f2d_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:cartographer.mapping.proto.TSDFRangeDataInserterOptions2D)
}
TSDFRangeDataInserterOptions2D::TSDFRangeDataInserterOptions2D(const TSDFRangeDataInserterOptions2D& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.has_normal_estimation_options()) {
    normal_estimation_options_ = new ::csmlio::mapping::proto::NormalEstimationOptions2D(*from.normal_estimation_options_);
  } else {
    normal_estimation_options_ = NULL;
  }
  ::memcpy(&truncation_distance_, &from.truncation_distance_,
    static_cast<size_t>(reinterpret_cast<char*>(&update_weight_distance_cell_to_hit_kernel_bandwidth_) -
    reinterpret_cast<char*>(&truncation_distance_)) + sizeof(update_weight_distance_cell_to_hit_kernel_bandwidth_));
  // @@protoc_insertion_point(copy_constructor:cartographer.mapping.proto.TSDFRangeDataInserterOptions2D)
}

void TSDFRangeDataInserterOptions2D::SharedCtor() {
  ::memset(&normal_estimation_options_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&update_weight_distance_cell_to_hit_kernel_bandwidth_) -
      reinterpret_cast<char*>(&normal_estimation_options_)) + sizeof(update_weight_distance_cell_to_hit_kernel_bandwidth_));
  _cached_size_ = 0;
}

TSDFRangeDataInserterOptions2D::~TSDFRangeDataInserterOptions2D() {
  // @@protoc_insertion_point(destructor:cartographer.mapping.proto.TSDFRangeDataInserterOptions2D)
  SharedDtor();
}

void TSDFRangeDataInserterOptions2D::SharedDtor() {
  if (this != internal_default_instance()) delete normal_estimation_options_;
}

void TSDFRangeDataInserterOptions2D::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* TSDFRangeDataInserterOptions2D::descriptor() {
  protobuf_cartographer_2fmapping_2fproto_2ftsdf_5frange_5fdata_5finserter_5foptions_5f2d_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_cartographer_2fmapping_2fproto_2ftsdf_5frange_5fdata_5finserter_5foptions_5f2d_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const TSDFRangeDataInserterOptions2D& TSDFRangeDataInserterOptions2D::default_instance() {
  protobuf_cartographer_2fmapping_2fproto_2ftsdf_5frange_5fdata_5finserter_5foptions_5f2d_2eproto::InitDefaults();
  return *internal_default_instance();
}

TSDFRangeDataInserterOptions2D* TSDFRangeDataInserterOptions2D::New(::google::protobuf::Arena* arena) const {
  TSDFRangeDataInserterOptions2D* n = new TSDFRangeDataInserterOptions2D;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void TSDFRangeDataInserterOptions2D::Clear() {
// @@protoc_insertion_point(message_clear_start:cartographer.mapping.proto.TSDFRangeDataInserterOptions2D)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaNoVirtual() == NULL && normal_estimation_options_ != NULL) {
    delete normal_estimation_options_;
  }
  normal_estimation_options_ = NULL;
  ::memset(&truncation_distance_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&update_weight_distance_cell_to_hit_kernel_bandwidth_) -
      reinterpret_cast<char*>(&truncation_distance_)) + sizeof(update_weight_distance_cell_to_hit_kernel_bandwidth_));
  _internal_metadata_.Clear();
}

bool TSDFRangeDataInserterOptions2D::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:cartographer.mapping.proto.TSDFRangeDataInserterOptions2D)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // double truncation_distance = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(9u /* 9 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &truncation_distance_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // double maximum_weight = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(17u /* 17 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &maximum_weight_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bool update_free_space = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u /* 24 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &update_free_space_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .cartographer.mapping.proto.NormalEstimationOptions2D normal_estimation_options = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(34u /* 34 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_normal_estimation_options()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bool project_sdf_distance_to_scan_normal = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(40u /* 40 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &project_sdf_distance_to_scan_normal_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 update_weight_range_exponent = 6;
      case 6: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(48u /* 48 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &update_weight_range_exponent_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // double update_weight_angle_scan_normal_to_ray_kernel_bandwidth = 7;
      case 7: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(57u /* 57 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &update_weight_angle_scan_normal_to_ray_kernel_bandwidth_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // double update_weight_distance_cell_to_hit_kernel_bandwidth = 8;
      case 8: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(65u /* 65 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &update_weight_distance_cell_to_hit_kernel_bandwidth_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:cartographer.mapping.proto.TSDFRangeDataInserterOptions2D)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:cartographer.mapping.proto.TSDFRangeDataInserterOptions2D)
  return false;
#undef DO_
}

void TSDFRangeDataInserterOptions2D::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:cartographer.mapping.proto.TSDFRangeDataInserterOptions2D)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // double truncation_distance = 1;
  if (this->truncation_distance() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(1, this->truncation_distance(), output);
  }

  // double maximum_weight = 2;
  if (this->maximum_weight() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(2, this->maximum_weight(), output);
  }

  // bool update_free_space = 3;
  if (this->update_free_space() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(3, this->update_free_space(), output);
  }

  // .cartographer.mapping.proto.NormalEstimationOptions2D normal_estimation_options = 4;
  if (this->has_normal_estimation_options()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      4, *this->normal_estimation_options_, output);
  }

  // bool project_sdf_distance_to_scan_normal = 5;
  if (this->project_sdf_distance_to_scan_normal() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(5, this->project_sdf_distance_to_scan_normal(), output);
  }

  // int32 update_weight_range_exponent = 6;
  if (this->update_weight_range_exponent() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(6, this->update_weight_range_exponent(), output);
  }

  // double update_weight_angle_scan_normal_to_ray_kernel_bandwidth = 7;
  if (this->update_weight_angle_scan_normal_to_ray_kernel_bandwidth() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(7, this->update_weight_angle_scan_normal_to_ray_kernel_bandwidth(), output);
  }

  // double update_weight_distance_cell_to_hit_kernel_bandwidth = 8;
  if (this->update_weight_distance_cell_to_hit_kernel_bandwidth() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(8, this->update_weight_distance_cell_to_hit_kernel_bandwidth(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:cartographer.mapping.proto.TSDFRangeDataInserterOptions2D)
}

::google::protobuf::uint8* TSDFRangeDataInserterOptions2D::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:cartographer.mapping.proto.TSDFRangeDataInserterOptions2D)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // double truncation_distance = 1;
  if (this->truncation_distance() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(1, this->truncation_distance(), target);
  }

  // double maximum_weight = 2;
  if (this->maximum_weight() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(2, this->maximum_weight(), target);
  }

  // bool update_free_space = 3;
  if (this->update_free_space() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(3, this->update_free_space(), target);
  }

  // .cartographer.mapping.proto.NormalEstimationOptions2D normal_estimation_options = 4;
  if (this->has_normal_estimation_options()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        4, *this->normal_estimation_options_, deterministic, target);
  }

  // bool project_sdf_distance_to_scan_normal = 5;
  if (this->project_sdf_distance_to_scan_normal() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(5, this->project_sdf_distance_to_scan_normal(), target);
  }

  // int32 update_weight_range_exponent = 6;
  if (this->update_weight_range_exponent() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(6, this->update_weight_range_exponent(), target);
  }

  // double update_weight_angle_scan_normal_to_ray_kernel_bandwidth = 7;
  if (this->update_weight_angle_scan_normal_to_ray_kernel_bandwidth() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(7, this->update_weight_angle_scan_normal_to_ray_kernel_bandwidth(), target);
  }

  // double update_weight_distance_cell_to_hit_kernel_bandwidth = 8;
  if (this->update_weight_distance_cell_to_hit_kernel_bandwidth() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(8, this->update_weight_distance_cell_to_hit_kernel_bandwidth(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:cartographer.mapping.proto.TSDFRangeDataInserterOptions2D)
  return target;
}

size_t TSDFRangeDataInserterOptions2D::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:cartographer.mapping.proto.TSDFRangeDataInserterOptions2D)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // .cartographer.mapping.proto.NormalEstimationOptions2D normal_estimation_options = 4;
  if (this->has_normal_estimation_options()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->normal_estimation_options_);
  }

  // double truncation_distance = 1;
  if (this->truncation_distance() != 0) {
    total_size += 1 + 8;
  }

  // double maximum_weight = 2;
  if (this->maximum_weight() != 0) {
    total_size += 1 + 8;
  }

  // bool update_free_space = 3;
  if (this->update_free_space() != 0) {
    total_size += 1 + 1;
  }

  // bool project_sdf_distance_to_scan_normal = 5;
  if (this->project_sdf_distance_to_scan_normal() != 0) {
    total_size += 1 + 1;
  }

  // int32 update_weight_range_exponent = 6;
  if (this->update_weight_range_exponent() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->update_weight_range_exponent());
  }

  // double update_weight_angle_scan_normal_to_ray_kernel_bandwidth = 7;
  if (this->update_weight_angle_scan_normal_to_ray_kernel_bandwidth() != 0) {
    total_size += 1 + 8;
  }

  // double update_weight_distance_cell_to_hit_kernel_bandwidth = 8;
  if (this->update_weight_distance_cell_to_hit_kernel_bandwidth() != 0) {
    total_size += 1 + 8;
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void TSDFRangeDataInserterOptions2D::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:cartographer.mapping.proto.TSDFRangeDataInserterOptions2D)
  GOOGLE_DCHECK_NE(&from, this);
  const TSDFRangeDataInserterOptions2D* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const TSDFRangeDataInserterOptions2D>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:cartographer.mapping.proto.TSDFRangeDataInserterOptions2D)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:cartographer.mapping.proto.TSDFRangeDataInserterOptions2D)
    MergeFrom(*source);
  }
}

void TSDFRangeDataInserterOptions2D::MergeFrom(const TSDFRangeDataInserterOptions2D& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:cartographer.mapping.proto.TSDFRangeDataInserterOptions2D)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.has_normal_estimation_options()) {
    mutable_normal_estimation_options()->::csmlio::mapping::proto::NormalEstimationOptions2D::MergeFrom(from.normal_estimation_options());
  }
  if (from.truncation_distance() != 0) {
    set_truncation_distance(from.truncation_distance());
  }
  if (from.maximum_weight() != 0) {
    set_maximum_weight(from.maximum_weight());
  }
  if (from.update_free_space() != 0) {
    set_update_free_space(from.update_free_space());
  }
  if (from.project_sdf_distance_to_scan_normal() != 0) {
    set_project_sdf_distance_to_scan_normal(from.project_sdf_distance_to_scan_normal());
  }
  if (from.update_weight_range_exponent() != 0) {
    set_update_weight_range_exponent(from.update_weight_range_exponent());
  }
  if (from.update_weight_angle_scan_normal_to_ray_kernel_bandwidth() != 0) {
    set_update_weight_angle_scan_normal_to_ray_kernel_bandwidth(from.update_weight_angle_scan_normal_to_ray_kernel_bandwidth());
  }
  if (from.update_weight_distance_cell_to_hit_kernel_bandwidth() != 0) {
    set_update_weight_distance_cell_to_hit_kernel_bandwidth(from.update_weight_distance_cell_to_hit_kernel_bandwidth());
  }
}

void TSDFRangeDataInserterOptions2D::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:cartographer.mapping.proto.TSDFRangeDataInserterOptions2D)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void TSDFRangeDataInserterOptions2D::CopyFrom(const TSDFRangeDataInserterOptions2D& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:cartographer.mapping.proto.TSDFRangeDataInserterOptions2D)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TSDFRangeDataInserterOptions2D::IsInitialized() const {
  return true;
}

void TSDFRangeDataInserterOptions2D::Swap(TSDFRangeDataInserterOptions2D* other) {
  if (other == this) return;
  InternalSwap(other);
}
void TSDFRangeDataInserterOptions2D::InternalSwap(TSDFRangeDataInserterOptions2D* other) {
  using std::swap;
  swap(normal_estimation_options_, other->normal_estimation_options_);
  swap(truncation_distance_, other->truncation_distance_);
  swap(maximum_weight_, other->maximum_weight_);
  swap(update_free_space_, other->update_free_space_);
  swap(project_sdf_distance_to_scan_normal_, other->project_sdf_distance_to_scan_normal_);
  swap(update_weight_range_exponent_, other->update_weight_range_exponent_);
  swap(update_weight_angle_scan_normal_to_ray_kernel_bandwidth_, other->update_weight_angle_scan_normal_to_ray_kernel_bandwidth_);
  swap(update_weight_distance_cell_to_hit_kernel_bandwidth_, other->update_weight_distance_cell_to_hit_kernel_bandwidth_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata TSDFRangeDataInserterOptions2D::GetMetadata() const {
  protobuf_cartographer_2fmapping_2fproto_2ftsdf_5frange_5fdata_5finserter_5foptions_5f2d_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_cartographer_2fmapping_2fproto_2ftsdf_5frange_5fdata_5finserter_5foptions_5f2d_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// TSDFRangeDataInserterOptions2D

// double truncation_distance = 1;
void TSDFRangeDataInserterOptions2D::clear_truncation_distance() {
  truncation_distance_ = 0;
}
double TSDFRangeDataInserterOptions2D::truncation_distance() const {
  // @@protoc_insertion_point(field_get:cartographer.mapping.proto.TSDFRangeDataInserterOptions2D.truncation_distance)
  return truncation_distance_;
}
void TSDFRangeDataInserterOptions2D::set_truncation_distance(double value) {
  
  truncation_distance_ = value;
  // @@protoc_insertion_point(field_set:cartographer.mapping.proto.TSDFRangeDataInserterOptions2D.truncation_distance)
}

// double maximum_weight = 2;
void TSDFRangeDataInserterOptions2D::clear_maximum_weight() {
  maximum_weight_ = 0;
}
double TSDFRangeDataInserterOptions2D::maximum_weight() const {
  // @@protoc_insertion_point(field_get:cartographer.mapping.proto.TSDFRangeDataInserterOptions2D.maximum_weight)
  return maximum_weight_;
}
void TSDFRangeDataInserterOptions2D::set_maximum_weight(double value) {
  
  maximum_weight_ = value;
  // @@protoc_insertion_point(field_set:cartographer.mapping.proto.TSDFRangeDataInserterOptions2D.maximum_weight)
}

// bool update_free_space = 3;
void TSDFRangeDataInserterOptions2D::clear_update_free_space() {
  update_free_space_ = false;
}
bool TSDFRangeDataInserterOptions2D::update_free_space() const {
  // @@protoc_insertion_point(field_get:cartographer.mapping.proto.TSDFRangeDataInserterOptions2D.update_free_space)
  return update_free_space_;
}
void TSDFRangeDataInserterOptions2D::set_update_free_space(bool value) {
  
  update_free_space_ = value;
  // @@protoc_insertion_point(field_set:cartographer.mapping.proto.TSDFRangeDataInserterOptions2D.update_free_space)
}

// .cartographer.mapping.proto.NormalEstimationOptions2D normal_estimation_options = 4;
bool TSDFRangeDataInserterOptions2D::has_normal_estimation_options() const {
  return this != internal_default_instance() && normal_estimation_options_ != NULL;
}
void TSDFRangeDataInserterOptions2D::clear_normal_estimation_options() {
  if (GetArenaNoVirtual() == NULL && normal_estimation_options_ != NULL) delete normal_estimation_options_;
  normal_estimation_options_ = NULL;
}
const ::csmlio::mapping::proto::NormalEstimationOptions2D& TSDFRangeDataInserterOptions2D::normal_estimation_options() const {
  const ::csmlio::mapping::proto::NormalEstimationOptions2D* p = normal_estimation_options_;
  // @@protoc_insertion_point(field_get:cartographer.mapping.proto.TSDFRangeDataInserterOptions2D.normal_estimation_options)
  return p != NULL ? *p : *reinterpret_cast<const ::csmlio::mapping::proto::NormalEstimationOptions2D*>(
      &::csmlio::mapping::proto::_NormalEstimationOptions2D_default_instance_);
}
::csmlio::mapping::proto::NormalEstimationOptions2D* TSDFRangeDataInserterOptions2D::mutable_normal_estimation_options() {
  
  if (normal_estimation_options_ == NULL) {
    normal_estimation_options_ = new ::csmlio::mapping::proto::NormalEstimationOptions2D;
  }
  // @@protoc_insertion_point(field_mutable:cartographer.mapping.proto.TSDFRangeDataInserterOptions2D.normal_estimation_options)
  return normal_estimation_options_;
}
::csmlio::mapping::proto::NormalEstimationOptions2D* TSDFRangeDataInserterOptions2D::release_normal_estimation_options() {
  // @@protoc_insertion_point(field_release:cartographer.mapping.proto.TSDFRangeDataInserterOptions2D.normal_estimation_options)
  
  ::csmlio::mapping::proto::NormalEstimationOptions2D* temp = normal_estimation_options_;
  normal_estimation_options_ = NULL;
  return temp;
}
void TSDFRangeDataInserterOptions2D::set_allocated_normal_estimation_options(::csmlio::mapping::proto::NormalEstimationOptions2D* normal_estimation_options) {
  delete normal_estimation_options_;
  normal_estimation_options_ = normal_estimation_options;
  if (normal_estimation_options) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:cartographer.mapping.proto.TSDFRangeDataInserterOptions2D.normal_estimation_options)
}

// bool project_sdf_distance_to_scan_normal = 5;
void TSDFRangeDataInserterOptions2D::clear_project_sdf_distance_to_scan_normal() {
  project_sdf_distance_to_scan_normal_ = false;
}
bool TSDFRangeDataInserterOptions2D::project_sdf_distance_to_scan_normal() const {
  // @@protoc_insertion_point(field_get:cartographer.mapping.proto.TSDFRangeDataInserterOptions2D.project_sdf_distance_to_scan_normal)
  return project_sdf_distance_to_scan_normal_;
}
void TSDFRangeDataInserterOptions2D::set_project_sdf_distance_to_scan_normal(bool value) {
  
  project_sdf_distance_to_scan_normal_ = value;
  // @@protoc_insertion_point(field_set:cartographer.mapping.proto.TSDFRangeDataInserterOptions2D.project_sdf_distance_to_scan_normal)
}

// int32 update_weight_range_exponent = 6;
void TSDFRangeDataInserterOptions2D::clear_update_weight_range_exponent() {
  update_weight_range_exponent_ = 0;
}
::google::protobuf::int32 TSDFRangeDataInserterOptions2D::update_weight_range_exponent() const {
  // @@protoc_insertion_point(field_get:cartographer.mapping.proto.TSDFRangeDataInserterOptions2D.update_weight_range_exponent)
  return update_weight_range_exponent_;
}
void TSDFRangeDataInserterOptions2D::set_update_weight_range_exponent(::google::protobuf::int32 value) {
  
  update_weight_range_exponent_ = value;
  // @@protoc_insertion_point(field_set:cartographer.mapping.proto.TSDFRangeDataInserterOptions2D.update_weight_range_exponent)
}

// double update_weight_angle_scan_normal_to_ray_kernel_bandwidth = 7;
void TSDFRangeDataInserterOptions2D::clear_update_weight_angle_scan_normal_to_ray_kernel_bandwidth() {
  update_weight_angle_scan_normal_to_ray_kernel_bandwidth_ = 0;
}
double TSDFRangeDataInserterOptions2D::update_weight_angle_scan_normal_to_ray_kernel_bandwidth() const {
  // @@protoc_insertion_point(field_get:cartographer.mapping.proto.TSDFRangeDataInserterOptions2D.update_weight_angle_scan_normal_to_ray_kernel_bandwidth)
  return update_weight_angle_scan_normal_to_ray_kernel_bandwidth_;
}
void TSDFRangeDataInserterOptions2D::set_update_weight_angle_scan_normal_to_ray_kernel_bandwidth(double value) {
  
  update_weight_angle_scan_normal_to_ray_kernel_bandwidth_ = value;
  // @@protoc_insertion_point(field_set:cartographer.mapping.proto.TSDFRangeDataInserterOptions2D.update_weight_angle_scan_normal_to_ray_kernel_bandwidth)
}

// double update_weight_distance_cell_to_hit_kernel_bandwidth = 8;
void TSDFRangeDataInserterOptions2D::clear_update_weight_distance_cell_to_hit_kernel_bandwidth() {
  update_weight_distance_cell_to_hit_kernel_bandwidth_ = 0;
}
double TSDFRangeDataInserterOptions2D::update_weight_distance_cell_to_hit_kernel_bandwidth() const {
  // @@protoc_insertion_point(field_get:cartographer.mapping.proto.TSDFRangeDataInserterOptions2D.update_weight_distance_cell_to_hit_kernel_bandwidth)
  return update_weight_distance_cell_to_hit_kernel_bandwidth_;
}
void TSDFRangeDataInserterOptions2D::set_update_weight_distance_cell_to_hit_kernel_bandwidth(double value) {
  
  update_weight_distance_cell_to_hit_kernel_bandwidth_ = value;
  // @@protoc_insertion_point(field_set:cartographer.mapping.proto.TSDFRangeDataInserterOptions2D.update_weight_distance_cell_to_hit_kernel_bandwidth)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace proto
}  // namespace mapping
}  // namespace csmlio

// @@protoc_insertion_point(global_scope)
