

# ros wrapper 配置参数

# string
map_frame : "map"
tracking_frame : "base_link"
published_frame : "base_link"
odom_frame : "odom"

# bool
use_pose_extrapolator : true
use_odometry : false
use_nav_sat : false
use_landmarks : false
provide_odom_frame : true
publish_frame_projected_to_2d : false
publish_tracked_pose : true

# int
num_laser_scans : 0
num_multi_echo_laser_scans : 0
num_subdivisions_per_laser_scan : 1
num_point_clouds : 1

# double 
lookup_transform_timeout_sec : 0.2
submap_publish_period_sec : 0.5
pose_publish_period_sec : 0.05
trajectory_publish_period_sec : 0.05
rangefinder_sampling_ratio : 1.
odometry_sampling_ratio : 1.
fixed_frame_pose_sampling_ratio : 1.
imu_sampling_ratio : 1.
landmarks_sampling_ratio : 1.