# # Copyright 2016 The Cartographer Authors
# #
# # Licensed under the Apache License, Version 2.0.

map_frame : map
tracking_frame : base_link
published_frame : base_link
odom_frame : odom
provide_odom_frame : true
publish_frame_projected_to_2d : false
publish_tracked_pose : true
use_odometry : false
use_nav_sat : false
use_landmarks : false
use_pose_extrapolator : true
num_laser_scans : 0
num_multi_echo_laser_scans : 0
num_subdivisions_per_laser_scan : 1
num_point_clouds : 1
lookup_transform_timeout_sec : 0.2
submap_publish_period_sec : 0.5         # 100毫秒。
pose_publish_period_sec : 0.03          # 决定了 PublishLocalTrajectoryData 的发布频率。
trajectory_publish_period_sec : 0.03    # 决定了 PublishTrajectoryNodeList & PublishLandmarkPosesList 的发布频率。
rangefinder_sampling_ratio : 1.
odometry_sampling_ratio : 1.
fixed_frame_pose_sampling_ratio : 1.
imu_sampling_ratio : 1.
landmarks_sampling_ratio : 1.


